### ISSUE TITLE
Support MacPorts

### ISSUE THREAD

**Issue by flarik** [kabisaict/maji#26]
The project should also support Macports, e.g. do not force Homebrew upon the developer.

Reminder for self:

```bash
#!/usr/bin/env bash

# Install required macports packages
while read macports_package; do
  sudo port install $macports_package
done<<HERE
phantomjs
nodejs
npm
gnupg
apache-ant
HERE
```

**Comment by pascalw** [comment]
Closing this as I don't feel that we need to support Macports, nor any package system for that matter. We currently install some dependencies automatically if Homebrew is available and I think we should even consider removing that too since we can't install all dependencies for any system people may be running.
